language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
    - php: 7.0
env:
  - IS_TRAVIS=true

before_install:
  - sudo apt-get update > /dev/null

install:
  # setup travis variables
  - sh -c ./myci/travis.sh
  - sh -c ./myci/bootstrap.sh # shared
  - sh -c ./myci/startup.sh # shared


before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

