sudo: required

language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
   - php: nightly
   - php: hhvm      # only until docker container can be built

services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
    - DOCKER_COMPOSE_VERSION=1.7.1

before_install:
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

  # reinstall docker-compose at specific version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - PHP_VERSION=":7.0" ORIENTDB_VERSION=":2.1.16" NEO4J_VERSION=":2.3" GREMLIN_VERSION=":3.0.0" docker-compose up -d
  - sleep 40
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

## The other option is to run bin/spider-dev AS the test
## But how to specify different php versions and builds?