language: php
php:
  - 5.6
  - nightly

sudo: required
services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
    - DOCKER_COMPOSE_VERSION=1.7.1
  matrix:
    - TEST_SCRIPT="bin/spider-dev --php=7.0 test"
    - TEST_SCRIPT="bin/spider-dev --php=5.6 test"
    - TEST_SCRIPT="bin/spider-dev --hhvm=latest test"
    - TEST_SCRIPT="bin/run-ci-test.sh"

matrix:
  exclude:
    - php: nightly
      env: TEST_SCRIPT="bin/spider-dev --php=7.0 test"
    - php: nightly
      env: TEST_SCRIPT="bin/spider-dev --php=5.6 test"
    - php: nightly
      env: TEST_SCRIPT="bin/spider-dev --hhvm=latest test"
    - php: 5.6
      env: TEST_SCRIPT="bin/run-ci-test.sh"
  allow_failures:
   - php: nightly

cache:
  directories:
    - ./vendor

before_install:
  # upgrade docker-engine to specific version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

  # reinstall docker-compose at specific version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - curl -sS https://getcomposer.org/installer | php
  - travis_retry php composer.phar install

before_script:
  - mkdir -p build/logs

script:
  - $TEST_SCRIPT

after_script:
  - php vendor/bin/coveralls -v