version: '2'
services:
  php:
    build: .
    image: spider/php
    container_name: spider_php
    links:
      - orientdb:orientdb
      - neo4j:neo4j

  orientdb:
    image: orientdb:2.1.16
    container_name: spider_orientdb
    environment:
      ORIENTDB_ROOT_PASSWORD: rootpwd
    ports:
       - "2424:2424"
       - "2480:2480"

  neo4j:
    image: neo4j:2.3
    container_name: spider_neo4j
    environment:
      NEO4J_AUTH: neo4j/j4oen
    ports:
       - "7474:7474"
    volumes:
       - /data