version: '2'
services:
  php:
    build: .
    links:
       - "orientdb:orientdb"

  orientdb:
    image: orientdb:latest
    environment:
      ORIENTDB_ROOT_PASSWORD: rootpwd
    ports:
       - "2424:2424"
       - "2480:2480"
