version: '2'
services:
  php:
    image: skooppaos/php7
    container_name: spider_php
    links:
      - orientdb:orientdb
      - neo4j:neo4j
    volumes:
      - ./:/spider
    working_dir: /spider
    environment:
      - SPIDER_DOCKER=true

  orientdb:
    image: orientdb:2.1.16 #:${ORIENTDB_VERSION}
    container_name: spider_orientdb
    environment:
      ORIENTDB_ROOT_PASSWORD: rootpwd
    ports:
       - "2424:2424"
       - "2480:2480"

  neo4j:
    image: neo4j:2.3 #:${NEO4J_VERSION}
    container_name: spider_neo4j
    environment:
      NEO4J_AUTH: neo4j/j4oen
    ports:
       - "7474:7474"
    volumes:
       - /data