version: '2'
services:
  php:
    build: .
    image: spider/php
    container_name: spider_php

  orientdb:
    image: orientdb:2.1.16
    container_name: spider_orientdb
    environment:
      ORIENTDB_ROOT_PASSWORD: rootpwd
    ports:
       - "2424:2424"
       - "2480:2480"
